Repository Goorm-OGJG/Da-It-Gym-BE, pull requests merged in 2023-11, with the labels that each got.

#11 Feat : DIG-54 운동일지 완료 구현
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseJournal.java
  src/main/java/com/ogjg/daitgym/journal/controller/ExerciseJournalController.java
  src/main/java/com/ogjg/daitgym/journal/dto/request/ExerciseJournalCompleteRequest.java
  src/main/java/com/ogjg/daitgym/journal/service/ExerciseJournalService.java
Labels: enhancement

#13 Feat : DIG-67 QueryDslConfig, QueryDslRepository 추가
  src/main/java/com/ogjg/daitgym/config/QuerydslConfig.java
  src/main/java/com/ogjg/daitgym/feed/repository/FeedExerciseJournalRepository.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/journal/repository/exercisehistory/ExerciseHistoryRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/journal/repository/exercisehistory/ExerciseHistoryRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/journal/repository/exerciselist/ExerciseListRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/journal/repository/exerciselist/ExerciseListRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalRepositoryImpl.java
Labels: enhancement

#16 Feat : DIG-74 유저 기본 조회 로직 생성 및 Role 수정
  src/main/java/com/ogjg/daitgym/domain/Role.java
  src/main/java/com/ogjg/daitgym/domain/User.java
  src/main/java/com/ogjg/daitgym/user/controller/UserController.java
  src/main/java/com/ogjg/daitgym/user/exception/NotFoundUser.java
  src/main/java/com/ogjg/daitgym/user/repository/UserRepository.java
  src/main/java/com/ogjg/daitgym/user/service/UserService.java
Labels: enhancement

#18 Feat : DIG-60 follow 목록 가져오기
  src/main/java/com/ogjg/daitgym/follow/controller/FollowController.java
  src/main/java/com/ogjg/daitgym/follow/dto/response/FollowListDto.java
  src/main/java/com/ogjg/daitgym/follow/dto/response/FollowListResponse.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepository.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
Labels: enhancement

#14 Feat : DIG-70 좋아요 기능 구현
  src/main/java/com/ogjg/daitgym/domain/RoutineLike.java
  src/main/java/com/ogjg/daitgym/domain/feed/FeedExerciseJournalLike.java
  src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/controller/FeedExerciseJournalLikeController.java
  src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/dto/FeedExerciseJournalLikeResponse.java
  src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/repository/FeedExerciseJournalLikeRepository.java
  src/main/java/com/ogjg/daitgym/like/feedExerciseJournal/service/FeedExerciseJournalLikeService.java
  src/main/java/com/ogjg/daitgym/like/routine/controller/RoutineLikeController.java
  src/main/java/com/ogjg/daitgym/like/routine/dto/RoutineLikeResponse.java
  src/main/java/com/ogjg/daitgym/like/routine/repository/RoutineLikeRepository.java
  src/main/java/com/ogjg/daitgym/like/routine/service/RoutineLikeService.java
Labels: enhancement

#19 Feat : DIG-81 Exercise 관련 패키지 분리, 운동부위로 운동 검색 구현
  src/main/java/com/ogjg/daitgym/domain/exercise/Exercise.java
  src/main/java/com/ogjg/daitgym/domain/exercise/ExercisePart.java
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseList.java
  src/main/java/com/ogjg/daitgym/exercise/controller/ExerciseController.java
  src/main/java/com/ogjg/daitgym/exercise/dto/response/ExerciseListDto.java
  src/main/java/com/ogjg/daitgym/exercise/dto/response/ExerciseListResponse.java
  src/main/java/com/ogjg/daitgym/exercise/exception/NotFoundExercise.java
  src/main/java/com/ogjg/daitgym/exercise/exception/NotFoundExercisePart.java
  src/main/java/com/ogjg/daitgym/exercise/repository/ExercisePartRepository.java
  src/main/java/com/ogjg/daitgym/exercise/repository/ExerciseRepository.java
  src/main/java/com/ogjg/daitgym/exercise/service/ExerciseService.java
  src/main/java/com/ogjg/daitgym/journal/repository/exercise/ExercisePartRepository.java
  src/main/java/com/ogjg/daitgym/journal/service/ExerciseJournalService.java
Labels: enhancement

#21 Feat : DIG-86 피드 운동일지 공유, 삭제 추가 구현
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseJournal.java
  src/main/java/com/ogjg/daitgym/journal/controller/ExerciseJournalController.java
  src/main/java/com/ogjg/daitgym/journal/dto/request/ExerciseJournalCompleteRequest.java
  src/main/java/com/ogjg/daitgym/journal/dto/request/ExerciseJournalShareRequest.java
  src/main/java/com/ogjg/daitgym/journal/service/ExerciseJournalService.java
Labels: enhancement

#26 Feat : CI/CD 구현
  .github/workflows/deployment.yaml
  .github/workflows/gradle_build.yaml
  Dockerfile
  docker-compose.yml
  src/main/java/com/ogjg/daitgym/config/HealthCheck.java
  src/main/java/com/ogjg/daitgym/domain/RoutineExercise.java
  src/main/java/com/ogjg/daitgym/like/routine/service/RoutineLikeService.java
Labels: enhancement

#29 Feat : DIG-99 운동일지 가져오기
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseHistory.java
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseJournalReplicationHistory.java
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseList.java
  src/main/java/com/ogjg/daitgym/feed/repository/FeedExerciseJournalRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/journal/controller/ExerciseJournalController.java
  src/main/java/com/ogjg/daitgym/journal/dto/request/ReplicationExerciseJournalRequest.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalReplicationHistoryRepository.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/journal/service/ExerciseJournalService.java
Labels: documentation, enhancement

#39 Fix : 운동과 운동부위의 잘못된 연관관계를 수정
  src/main/java/com/ogjg/daitgym/domain/exercise/Exercise.java
  src/main/java/com/ogjg/daitgym/domain/exercise/ExercisePart.java
Labels: bug

#41 fix : JPA 관계 설정 시 객체 초기화
  src/main/java/com/ogjg/daitgym/domain/routine/Day.java
Labels: bug

#42 fix : DIG-112 루틴 API 버그 수정(Entity, DTO, 로직)
  src/main/java/com/ogjg/daitgym/domain/routine/Day.java
  src/main/java/com/ogjg/daitgym/routine/dto/RoutineDetailsResponseDto.java
  src/main/java/com/ogjg/daitgym/routine/dto/RoutineDto.java
  src/main/java/com/ogjg/daitgym/routine/dto/RoutineListResponseDto.java
  src/main/java/com/ogjg/daitgym/routine/service/RoutineService.java
Labels: bug

#40 Feat : DIG-92 채팅 기능 구현 수정
  src/main/java/com/ogjg/daitgym/chat/dto/ChatMessageDto.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
Labels: bug

#44 Fix : DIG-111 default HealthClub 생성 오류 수정
  src/main/java/com/ogjg/daitgym/user/service/AuthService.java
Labels: bug

#45 Fix : DIG-111 프로필 불러오기 응답 값에 프로필 관련 정보 추가
  src/main/java/com/ogjg/daitgym/user/dto/response/GetInbodiesResponse.java
  src/main/java/com/ogjg/daitgym/user/dto/response/GetUserProfileGetResponse.java
  src/main/java/com/ogjg/daitgym/user/service/UserService.java
Labels: enhancement

#46 fix : DIG-112 루틴 상세 조회 로직 변경
  src/main/java/com/ogjg/daitgym/domain/routine/ExerciseDetail.java
  src/main/java/com/ogjg/daitgym/routine/dto/RoutineDetailsResponseDto.java
  src/main/java/com/ogjg/daitgym/routine/service/RoutineService.java
Labels: bug

#47 fix : DIG-112 루틴 목록 조회 정렬 조건 수정 및 로직 수정
  src/main/java/com/ogjg/daitgym/routine/controller/RoutineController.java
  src/main/java/com/ogjg/daitgym/routine/service/RoutineService.java
Labels: bug

#48 Refactor : 팔로우 Dto명 변경, email에서 nickname으로 조회로직 변경
  src/main/java/com/ogjg/daitgym/follow/controller/FollowController.java
  src/main/java/com/ogjg/daitgym/follow/dto/request/FollowRequest.java
  src/main/java/com/ogjg/daitgym/follow/dto/response/FollowCountResponse.java
  src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
Labels: enhancement

#50 Feat : DIG-92 채팅시 필요한 이미지값 추가
  src/main/java/com/ogjg/daitgym/chat/controller/ChatMessageController.java
  src/main/java/com/ogjg/daitgym/chat/controller/ChatRoomController.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatMessageDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatRoomDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/CreateChatRoomRequest.java
  src/main/java/com/ogjg/daitgym/chat/repository/ChatMessageRepository.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatRoomService.java
  src/main/java/com/ogjg/daitgym/domain/ChatMessage.java
Labels: enhancement

#55 Feat : DIG-126 User 찾아올 때, email이 아닌 nickname으로 가져오기
  src/main/java/com/ogjg/daitgym/chat/controller/ChatRoomController.java
  src/main/java/com/ogjg/daitgym/chat/dto/FindAllChatRoomRequest.java
  src/main/java/com/ogjg/daitgym/chat/repository/ChatMessageRepository.java
  src/main/java/com/ogjg/daitgym/chat/repository/ChatRoomRepository.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatRoomService.java
Labels: enhancement

#60 Feat : DIG-130 프론트와 서버 연결을 위한 수정
  src/main/java/com/ogjg/daitgym/config/websocket/StompHandler.java
  src/main/java/com/ogjg/daitgym/config/websocket/WebSockConfig.java
Labels: enhancement

#64 Feat : DIG-132 채팅 읽음/안읽음 표시 관련된 누락 코드 추가
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/config/websocket/StompHandler.java
Labels: bug

#68 Chore : Domain별 Exception 패키지 위치 변경
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatRoomService.java
  src/main/java/com/ogjg/daitgym/common/exception/exercise/NotFoundExercise.java
  src/main/java/com/ogjg/daitgym/common/exception/exercise/NotFoundExercisePart.java
  src/main/java/com/ogjg/daitgym/common/exception/feed/AlreadyExistFeedJournal.java
  src/main/java/com/ogjg/daitgym/common/exception/feed/AlreadyExistFeedJournalCollection.java
  src/main/java/com/ogjg/daitgym/common/exception/feed/NotFoundFeedJournalCollection.java
  src/main/java/com/ogjg/daitgym/common/exception/feed/NotFoundFeedJournalImage.java
  src/main/java/com/ogjg/daitgym/common/exception/feed/RangeOverImages.java
  src/main/java/com/ogjg/daitgym/common/exception/follow/AlreadyFollowUser.java
  src/main/java/com/ogjg/daitgym/common/exception/follow/NotFoundFollow.java
  src/main/java/com/ogjg/daitgym/common/exception/journal/AlreadyExistExerciseJournal.java
  src/main/java/com/ogjg/daitgym/common/exception/journal/NotFoundExerciseHistory.java
  src/main/java/com/ogjg/daitgym/common/exception/journal/NotFoundExerciseList.java
  src/main/java/com/ogjg/daitgym/common/exception/journal/NotFoundJournal.java
  src/main/java/com/ogjg/daitgym/common/exception/journal/UserNotAuthorizedForJournal.java
  src/main/java/com/ogjg/daitgym/common/exception/routine/AlreadyScrappedRoutine.java
  src/main/java/com/ogjg/daitgym/common/exception/routine/NoExerciseInRoutine.java
  src/main/java/com/ogjg/daitgym/common/exception/routine/NotFoundScrappedUserRoutine.java
  src/main/java/com/ogjg/daitgym/common/exception/user/AlreadyExistNickname.java
  src/main/java/com/ogjg/daitgym/common/exception/user/EmptyTrainerApplyException.java
  src/main/java/com/ogjg/daitgym/common/exception/user/NotFoundHealthClub.java
  src/main/java/com/ogjg/daitgym/common/exception/user/NotFoundSplitTitle.java
  src/main/java/com/ogjg/daitgym/common/exception/user/NotFoundUser.java
  src/main/java/com/ogjg/daitgym/common/exception/user/UnauthorizedUser.java
  src/main/java/com/ogjg/daitgym/domain/ExerciseSplit.java
  src/main/java/com/ogjg/daitgym/exercise/service/ExerciseService.java
  src/main/java/com/ogjg/daitgym/feed/service/FeedExerciseJournalService.java
  src/main/java/com/ogjg/daitgym/feed/service/FeedJournalHelperService.java
  src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
  src/main/java/com/ogjg/daitgym/journal/service/ExerciseJournalService.java
  src/main/java/com/ogjg/daitgym/routine/service/RoutineService.java
  src/main/java/com/ogjg/daitgym/user/service/UserService.java
Labels: enhancement

#71 Fix : DIG-111 통계 누적 버그 수정
  src/main/java/com/ogjg/daitgym/user/dto/response/GetInbodiesResponse.java
Labels: bug

#69 Fix : DIG-111 로그인 로직 초깃값 버그 수정, Value 주입 방식 변경 및 리팩터링
  src/main/java/com/ogjg/daitgym/user/controller/LoginController.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KakaoAccountResponse.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KakaoTokenResponse.java
  src/main/java/com/ogjg/daitgym/user/dto/response/LoginResponse.java
  src/main/java/com/ogjg/daitgym/user/service/AuthService.java
Labels: bug

#72 Refactor : DIG-138 채팅 코드 리팩토링
  src/main/java/com/ogjg/daitgym/chat/controller/ChatMessageController.java
  src/main/java/com/ogjg/daitgym/chat/controller/ChatRoomController.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatMessageDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatRoomDto.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatRoomResponse.java
  src/main/java/com/ogjg/daitgym/chat/dto/ChatRoomsResponse.java
  src/main/java/com/ogjg/daitgym/chat/dto/SelectedChatRoomResponse.java
  src/main/java/com/ogjg/daitgym/chat/repository/ChatMessageRepository.java
  src/main/java/com/ogjg/daitgym/chat/repository/ChatRoomRepository.java
  src/main/java/com/ogjg/daitgym/chat/repository/UsersChattingRoomRepository.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatRoomService.java
  src/main/java/com/ogjg/daitgym/common/exception/chat/NotFoundChattingRoom.java
  src/main/java/com/ogjg/daitgym/common/exception/chat/StompExceptionHandler.java
  src/main/java/com/ogjg/daitgym/common/exception/chat/UnauthorizedException.java
  src/main/java/com/ogjg/daitgym/config/security/jwt/util/JwtUtils.java
  src/main/java/com/ogjg/daitgym/config/websocket/StompHandler.java
  src/main/java/com/ogjg/daitgym/config/websocket/WebSockConfig.java
  src/main/java/com/ogjg/daitgym/domain/ChatMessage.java
  src/main/java/com/ogjg/daitgym/domain/ChatRoom.java
Labels: enhancement

#75 Fix : DIG-13 전체 메세지 조회 버그 수정
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
Labels: bug

#74 Refactor : 운동일지 생성 후 운동일지Id를 반환, ErrorCode 정리
  src/main/java/com/ogjg/daitgym/common/exception/ErrorCode.java
  src/main/java/com/ogjg/daitgym/journal/controller/ExerciseJournalController.java
Labels: enhancement

#80 Fix : 임시 admin 접근 권한 허용
  src/main/java/com/ogjg/daitgym/config/security/SecurityConfig.java
Labels: bug, help wanted, invalid

#79 Fix : DIG-148 채팅방 중복 생성 버그 수정 및 필요 없는 코드 삭제
  src/main/java/com/ogjg/daitgym/chat/repository/UsersChattingRoomRepository.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatMessageService.java
  src/main/java/com/ogjg/daitgym/chat/service/ChatRoomService.java
Labels: bug

#84 Fix : DIG-155 메세지 보낼 때, 사용자의 토큰 유효성 검사 로직 추가
  src/main/java/com/ogjg/daitgym/config/websocket/StompHandler.java
Labels: enhancement

#83 Fix: 팔로우 목록보기시 인바디 수 만큼 사용자가 늘어나는 버그 수정
  src/main/java/com/ogjg/daitgym/follow/dto/response/FollowListDto.java
  src/main/java/com/ogjg/daitgym/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/follow/service/FollowService.java
  src/main/java/com/ogjg/daitgym/user/repository/InbodyRepository.java
Labels: bug

#88 Fix : DIG-143 승인 요청 상세에 누락된 role 추가
  src/main/java/com/ogjg/daitgym/admin/dto/response/GetApprovalDetailResponse.java
Labels: bug

#91 Fix DIG-160: 카카오 소셜 친구목록 받아오기
  src/main/java/com/ogjg/daitgym/common/exception/ErrorCode.java
  src/main/java/com/ogjg/daitgym/common/exception/user/NotFoundUserAuthentication.java
  src/main/java/com/ogjg/daitgym/domain/UserAuthentication.java
  src/main/java/com/ogjg/daitgym/user/controller/UserFriendController.java
  src/main/java/com/ogjg/daitgym/user/dto/request/KaKaoFriendRequest.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KaKaoFriendResponseDto.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KaKaoFriendsResponse.java
  src/main/java/com/ogjg/daitgym/user/repository/UserAuthenticationRepository.java
  src/main/java/com/ogjg/daitgym/user/service/KakaoFriendService.java
Labels: enhancement

#93 Fix DIG-160: 카카오 소셜 Exception 추가
  src/main/java/com/ogjg/daitgym/common/exception/ErrorCode.java
  src/main/java/com/ogjg/daitgym/common/exception/user/ForbiddenKaKaoSocial.java
  src/main/java/com/ogjg/daitgym/config/security/jwt/util/JwtUtils.java
  src/main/java/com/ogjg/daitgym/user/controller/UserFriendController.java
  src/main/java/com/ogjg/daitgym/user/service/KakaoFriendService.java
Labels: enhancement

#95 Fix DIG-160: 카카오 소셜 Exception 추가
  src/main/java/com/ogjg/daitgym/domain/journal/ExerciseJournal.java
  src/main/java/com/ogjg/daitgym/user/service/KakaoFriendService.java
Labels: enhancement

#96 Fix DIG-160: 카카오 소셜 log 추가
  src/main/java/com/ogjg/daitgym/user/service/AuthService.java
Labels: enhancement

#90 Feat : DIG-161 운동일지 웹푸시 알람보내기
  .gitignore
  build.gradle
  src/main/java/com/ogjg/daitgym/DaItGymApplication.java
  src/main/java/com/ogjg/daitgym/alarm/controller/fcm/NotificationApiController.java
  src/main/java/com/ogjg/daitgym/alarm/dto/FcmTokenRequestDto.java
  src/main/java/com/ogjg/daitgym/alarm/dto/NotificationRequestDto.java
  src/main/java/com/ogjg/daitgym/alarm/repository/FcmTokenRepository.java
  src/main/java/com/ogjg/daitgym/alarm/service/FCMInitializer.java
  src/main/java/com/ogjg/daitgym/alarm/service/FcmAlarmService.java
  src/main/java/com/ogjg/daitgym/alarm/service/ScheduledService.java
  src/main/java/com/ogjg/daitgym/common/exception/ErrorCode.java
  src/main/java/com/ogjg/daitgym/common/exception/fcmtoken/NotFoundFcmToken.java
  src/main/java/com/ogjg/daitgym/domain/FcmToken.java
  src/main/java/com/ogjg/daitgym/journal/repository/exerciselist/ExerciseListRepository.java
  src/main/java/com/ogjg/daitgym/journal/repository/journal/ExerciseJournalRepository.java
  src/main/java/com/ogjg/daitgym/user/controller/UserController.java
Labels: enhancement

#98 Fix DIG-160: 카카오 소셜 친구목록 받아오기
  src/main/java/com/ogjg/daitgym/user/dto/request/KaKaoFriendsRequest.java
  src/main/java/com/ogjg/daitgym/user/dto/request/KaKaoFriendsRequestDto.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KaKaoFriendResponseDto.java
  src/main/java/com/ogjg/daitgym/user/dto/response/KaKaoFriendsResponse.java
  src/main/java/com/ogjg/daitgym/user/service/KakaoFriendService.java
Labels: enhancement

#101 Feat : cors 설정 수정
  src/main/java/com/ogjg/daitgym/config/security/SecurityConfig.java
Labels: documentation

#103 Fix : DIG-177 FCM 웹 푸시 버그 수정
  src/main/java/com/ogjg/daitgym/alarm/controller/fcm/FcmTokenController.java
  src/main/java/com/ogjg/daitgym/alarm/controller/fcm/NotificationApiController.java
  src/main/java/com/ogjg/daitgym/alarm/repository/FcmTokenRepository.java
  src/main/java/com/ogjg/daitgym/alarm/service/FcmAlarmService.java
  src/main/java/com/ogjg/daitgym/alarm/service/FcmTokenService.java
  src/main/java/com/ogjg/daitgym/alarm/service/ScheduledService.java
  src/main/java/com/ogjg/daitgym/domain/FcmToken.java
  src/main/java/com/ogjg/daitgym/user/controller/UserController.java
Labels: bug

#104 Fix : DIG-181 FCM 웹 푸시 시간 수정
  src/main/java/com/ogjg/daitgym/alarm/service/ScheduledService.java
Labels: bug

#105 Fix : fetchJoin으로 인한 중복값으로 인해 페이징시목록이 제대로 호출되지 않는 버그 수정
  src/main/java/com/ogjg/daitgym/feed/repository/FeedExerciseJournalRepositoryCustom.java
  src/main/java/com/ogjg/daitgym/feed/repository/FeedExerciseJournalRepositoryImpl.java
  src/main/java/com/ogjg/daitgym/feed/service/FeedExerciseJournalService.java
  src/main/java/com/ogjg/daitgym/feed/service/FeedJournalHelper.java
  src/main/java/com/ogjg/daitgym/feed/service/UserFeedExerciseJournalService.java
Labels: enhancement

#106 Fix : fetchJoin으로 버그 수정
  src/main/java/com/ogjg/daitgym/feed/repository/FeedExerciseJournalRepositoryImpl.java
Labels: bug
